/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-01-02 18:44:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tests.basic;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <title>Site Login</title>\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("\n");
      out.write("    body {background-color:white;}\n");
      out.write("    H1 {font-size:28pt; \n");
      out.write("        background-color:lightblue;    \n");
      out.write("        font-family:verdana;\n");
      out.write("        color:black;\n");
      out.write("        height:113;\n");
      out.write("        margin:5px\n");
      out.write("    }\n");
      out.write("    form {font-size:12pt; \n");
      out.write("          background-color:white;    \n");
      out.write("          font-family:verdana;\n");
      out.write("          height:175;\n");
      out.write("          width:200;\n");
      out.write("          border:2px solid grey;\n");
      out.write("          padding:1px;\n");
      out.write("          margin:5px\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  <hr/>\n");
      out.write("  <H1>\n");
      out.write("    <img src=\"logo.png\" alt=\"Logo\" style=\"width:355px;height:113px\">\n");
      out.write("    Site Login \n");
      out.write("  </H1>\n");
      out.write("  <hr/>\n");
      out.write("  <form name=\"login\" action=\"login\" method=\"POST\">\n");
      out.write("      <pre>\n");
      out.write(" USERNAME:   <input type=\"text\" name=\"user\" size=\"7\" value=\"\">\n");
      out.write("      <br/>\n");
      out.write(" PASSWORD:   <input type=\"text\" name=\"pass\" size=\"7\" value=\"\">\n");
      out.write("      <br/>\n");
      out.write("        <input type=\"submit\" value=\"Log In\">\n");
      out.write("      <pre/>\n");
      out.write("  </form>\n");
      out.write("<html/>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
