/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-01-06 22:57:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Accreditation Login</title>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\tmargin:0; \n");
      out.write("\tpadding:0;\n");
      out.write("\tbackground-color:#999;\n");
      out.write("\twidth: auto;\n");
      out.write("\tfloat: none;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("main {\n");
      out.write("\tposition: static;\n");
      out.write("\tmargin-right: auto;\n");
      out.write("\tmargin-left: auto;\n");
      out.write("\twidth: 70%;\n");
      out.write("\n");
      out.write("\tmargin-top:auto;\n");
      out.write("\tmargin-bottom:auto;\n");
      out.write("\twidth:50%;\n");
      out.write("\n");
      out.write("\n");
      out.write("\tbox-shadow:5px 5px 20px #000;\n");
      out.write("\tbackground-color:#FFF;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("img {\n");
      out.write("\tborder:none;\n");
      out.write("\t}\t\n");
      out.write("\t\n");
      out.write("/*Header*/\n");
      out.write(".block-type-header {\n");
      out.write("\twidth: auto;\n");
      out.write("\theight: 113px;\n");
      out.write("\tbackground-color: #2A3E73;\n");
      out.write("\ttext-align: center;\n");
      out.write("\t}\t\n");
      out.write("\t\n");
      out.write("/*Footer*/\n");
      out.write(".block-type-footer { \n");
      out.write("\tbackground:#293f6f; overflow:hidden;\n");
      out.write("\tpadding-left: 0px;\n");
      out.write("\tpadding-right: 0px;\n");
      out.write("\tbox-shadow: 5px 5px 20px #000;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write(".footer-left {\n");
      out.write("\tmargin-top:0px;\n");
      out.write("\tmargin-left:0px;\t\n");
      out.write("\tfloat:left;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write(".footer-right {\n");
      out.write("\tmargin-top:20px;\t\n");
      out.write("\tmargin-right:10px;\n");
      out.write("\tfloat:right;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write(".block-type-footer a {\n");
      out.write("\tfont-family: Open Sans, sans-serif;\n");
      out.write("\tcolor:#fff;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write(".block-type-footer a:hover {\n");
      out.write("\tcolor:#00aeef;\n");
      out.write("\t}\t\n");
      out.write("\n");
      out.write(".block-type-footer p.copyright {\n");
      out.write("\tfont-size: 15px;\t\n");
      out.write("\tfont-family: Open Sans, sans-serif;\n");
      out.write("\tcolor:#C9DAEA;\n");
      out.write("\tline-height:140%;\n");
      out.write("\ttext-align: left;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("/*Login*/\n");
      out.write(".login-form {\n");
      out.write("\twidth: 300px;\n");
      out.write("\tmargin: 10px auto;\n");
      out.write("\tposition: relative;\n");
      out.write("\tbackground-color: #C9DAEA;\n");
      out.write("\tborder-radius: 4px;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write(".login-form .login-header {\n");
      out.write("\tpadding: 5px 30px 0px 30px;\n");
      out.write("\t}\t\n");
      out.write("\n");
      out.write(".login-form .login-header h2 {\n");
      out.write("\tfont-family: Open Sans, sans-serif; \n");
      out.write("\tcolor:  #293f6f;\n");
      out.write("\tfont-size: 26px;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("\tfont-weight: normal;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write(".login-form .login-header p, .login-form .login-content p, .login-form .login-footer p  {\n");
      out.write("\tfont-family: EB Garamond, serif;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("    line-height: 140%;\n");
      out.write("\tcolor: #293F6F;\n");
      out.write("    margin-top: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form .login-footer a {\n");
      out.write("\ttext-decoration:none; \n");
      out.write("\tfont-family: Open Sans, sans-serif; \n");
      out.write("\tfont-size:16px;\n");
      out.write("\tcolor:  #293f6f;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write(".login-form .login-footer a:hover {\n");
      out.write("\tcolor: #DBE7F1\n");
      out.write("\t}\n");
      out.write("\n");
      out.write(".login-form .login-content {\n");
      out.write("\tpadding: 0 30px 20px 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form .login-content .input {\n");
      out.write("\twidth: 188px;\n");
      out.write("\tpadding: 15px 25px;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\tcolor: #293f6f;\n");
      out.write("\tbackground: #fff;\n");
      out.write("\tborder: 1px solid #fff;\n");
      out.write("\tborder-radius: 4px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form .login-content .password, .login-form .login-content .pass-icon {\n");
      out.write("\tmargin-top: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form .login-content .input:hover {\n");
      out.write("\tbackground: #C9DAEA;\n");
      out.write("\tcolor: #293f6f;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form .login-content .input:focus {\n");
      out.write("\tbackground: #E6F7FD; \n");
      out.write("\tcolor: #293f6f;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\n");
      out.write(".login-form .login-footer {\n");
      out.write("\tpadding: 10px 30px 5px 30px;\n");
      out.write("\toverflow: auto;\n");
      out.write("\tbackground: #92B6D5;\n");
      out.write("    border-bottom-right-radius: 4px;      \n");
      out.write("    border-bottom-left-radius: 4px;        \n");
      out.write("\t}\n");
      out.write("\n");
      out.write(".login-form .login-footer .login-button {\n");
      out.write("\tpadding: 11px  25px;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\tcolor: #fff;\n");
      out.write("\tbackground: #4A85B9;\n");
      out.write("\tborder: none;\n");
      out.write("\tborder-radius: 4px;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form .login-footer .login-button:hover {\n");
      out.write("\tbackground: #00aeef ;\n");
      out.write("\tborder: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form .login-footer .login-button:focus {\n");
      out.write("\tposition: relative;\n");
      out.write("\tbottom: -1px;\n");
      out.write("    color: #00AEEF;\t\n");
      out.write("    background: #E6F7FD;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("</style>\n");
      out.write("</br></br></br>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<main>\n");
      out.write("\n");
      out.write("<div class=\"block-type-header\">\n");
      out.write("<a href=\"http://tcnj.pages.tcnj.edu/\"><img src=\"images/logo.png\" /></a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<form class=\"login-form\" id=\"login\" action=\"jsp/welcome.jsp\" method=\"post\" name=\"login-form\" autocomplete=off onSubmit=\"\">\n");
      out.write("<input type=\"hidden\" name=\"timezoneOffset\" value=\"0\">\n");
      out.write("\n");
      out.write("<div class=\"login-header\">\n");
      out.write("<h2>Accrediation Site</h2>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"login-content\"><input class=\"input username\" id=\"userid\" type=\"text\" name=\"userid\" placeholder=\"Username\" />\n");
      out.write("<input class=\"input password\" id=\"pwd\" type=\"password\" name=\"pwd\" placeholder=\"Password\" /></div>\n");
      out.write("\n");
      out.write("<div class=\"login-footer\"><input class=\"login-button\" type=\"submit\" name=\"submit\" value=\"Sign In\" /></div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"block-type-footer\">\n");
      out.write("<div class=\"footer-left\"><a href=\"http://www.tcnj.edu/\"><img class=\"alignleft size-full\" alt=\"logo\" src=\"images/logo150x120.jpg\" width=\"150\" height=\"120\" /></a></div>\n");
      out.write("\n");
      out.write("<div class=\"footer-right\"><p class=\"copyright\">2000 Pennington Road<br />Ewing, NJ 08628-0718</p></div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</main>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
